language: java
services:
  - docker
env:
  global:
  - GCP_PROJECT_ID=pingponggcp
  - IMAGE=gcr.io/pingponggcp/helloworld
  - CLOUD_RUN_SERVICE=helloworld
  - CLOUD_RUN_REGION=us-central1
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
- openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv -in google-key.json.enc -out google-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=google-key.json
- gcloud auth configure-docker
- gcloud config set project "${GCP_PROJECT_ID}"
- gcloud components install beta

install: true # no-op

script:
- |
  set -ex;
  docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
  docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
  gcloud beta run deploy "${CLOUD_RUN_SERVICE}-2" \
    --image="${IMAGE}:${TRAVIS_COMMIT}" \
    --platform=managed \
    --region="${CLOUD_RUN_REGION}" \
    --allow-unauthenticated;
  set +x